-- =====================================================================
--  Sapphire Stock - database setup for Supabase
--  Every write goes through the functions below, which check the
--  user's permissions and record the change for the admin to review.
-- =====================================================================

create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------- tables

create table public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  username    text not null unique,
  full_name   text,
  role        text not null default 'worker' check (role in ('admin', 'worker')),
  perms       text[] not null default '{}',
  active      boolean not null default true,
  must_change boolean not null default true,
  created_at  timestamptz not null default now()
);

create table public.products (
  id            bigint generated by default as identity primary key,
  name          text not null,
  category      text not null default 'Other',
  sell          numeric,
  reorder_level numeric not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now()
);
create unique index products_name_ci on public.products (lower(name));

-- Buying prices live apart so workers without "see prices" cannot read them.
create table public.product_costs (
  product_id bigint primary key references public.products(id) on delete cascade,
  buy        numeric
);

create table public.periods (
  id         bigint generated by default as identity primary key,
  name       text not null,
  status     text not null default 'open' check (status in ('open', 'closed')),
  created_at timestamptz not null default now(),
  closed_at  timestamptz,
  closed_by  text
);
create unique index periods_one_open on public.periods (status) where status = 'open';

create table public.lines (
  period_id  bigint not null references public.periods(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  opening    numeric not null default 0,
  closing    numeric,               -- the count; null = not counted yet
  sell       numeric,               -- selling price saved when the period closes
  counted_by text,
  counted_at timestamptz,
  primary key (period_id, product_id)
);

create table public.line_costs (   -- buying price saved when the period closes
  period_id  bigint not null references public.periods(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  buy        numeric,
  primary key (period_id, product_id)
);

create table public.movements (    -- 'in' = delivery received, 'out' = removed, not sold
  id         bigint generated by default as identity primary key,
  period_id  bigint not null references public.periods(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  type       text not null check (type in ('in', 'out')),
  qty        numeric not null check (qty > 0),
  note       text,
  created_by text,
  created_at timestamptz not null default now()
);
create index movements_period on public.movements (period_id);

create table public.changes (      -- audit log the admin reviews
  id           bigint generated by default as identity primary key,
  ts           timestamptz not null default now(),
  user_id      uuid,
  username     text,
  action       text not null,
  product_id   bigint,
  product_name text,
  period_id    bigint,
  field        text,
  old_value    text,
  new_value    text,
  note         text,
  seen         boolean not null default false
);
create index changes_seen on public.changes (seen) where not seen;

-- ---------------------------------------------------------------- helpers

create function public.is_active() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from profiles where id = auth.uid() and active)
$$;

create function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from profiles where id = auth.uid() and active and role = 'admin')
$$;

create function public.has_perm(p text) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from profiles
                 where id = auth.uid() and active and (role = 'admin' or p = any (perms)))
$$;

create function public.my_name() returns text
language sql stable security definer set search_path = public as $$
  select username from profiles where id = auth.uid()
$$;

create function public.open_period_id() returns bigint
language sql stable security definer set search_path = public as $$
  select id from periods where status = 'open' order by id desc limit 1
$$;

create function public.fmt(x numeric) returns text
language sql immutable as $$ select trim_scale(x)::text $$;

create function public.allowed_perms() returns text[]
language sql immutable as $$
  select array['count', 'receive', 'add_products', 'see_expected', 'see_prices', 'reports', 'close']
$$;

create function public.need(p text) returns void
language plpgsql stable security definer set search_path = public as $$
begin
  if not has_perm(p) then
    raise exception 'You are not allowed to do this' using errcode = '42501';
  end if;
end $$;

create function public.log_change(p_action text, p_product bigint, p_period bigint, p_field text,
                                  p_old text, p_new text, p_note text) returns void
language sql security definer set search_path = public as $$
  insert into changes (user_id, username, action, product_id, product_name, period_id,
                       field, old_value, new_value, note, seen)
  values (auth.uid(), coalesce(my_name(), 'system'), p_action, p_product,
          (select name from products where id = p_product), p_period,
          p_field, p_old, p_new, p_note, is_admin())   -- admin's own edits need no review
$$;

-- ---------------------------------------------------------------- counting & deliveries

create function public.set_count(p_product bigint, p_qty numeric) returns void
language plpgsql security definer set search_path = public as $$
declare
  per bigint := open_period_id();
  old numeric;
begin
  perform need('count');
  if per is null then raise exception 'No open stock take'; end if;
  if p_qty < 0 then raise exception 'Count cannot be negative'; end if;
  insert into lines (period_id, product_id) values (per, p_product) on conflict do nothing;
  select closing into old from lines where period_id = per and product_id = p_product for update;
  if old is not distinct from p_qty then return; end if;
  update lines
     set closing = p_qty,
         counted_by = case when p_qty is null then null else my_name() end,
         counted_at = case when p_qty is null then null else now() end
   where period_id = per and product_id = p_product;
  perform log_change('count', p_product, per, 'count', fmt(old), fmt(p_qty),
                     case when p_qty is null then 'count cleared' end);
end $$;

create function public.add_movement(p_product bigint, p_type text, p_qty numeric,
                                    p_note text default null, p_cost numeric default null,
                                    p_update_cost boolean default false) returns void
language plpgsql security definer set search_path = public as $$
declare
  per bigint := open_period_id();
  old_cost numeric;
  nt text := nullif(trim(p_note), '');
begin
  perform need('receive');
  if per is null then raise exception 'No open stock take'; end if;
  if p_type not in ('in', 'out') then raise exception 'Invalid type'; end if;
  if p_qty is null or p_qty <= 0 then raise exception 'Quantity must be more than zero'; end if;
  if not exists (select 1 from products where id = p_product) then raise exception 'Unknown product'; end if;
  insert into lines (period_id, product_id) values (per, p_product) on conflict do nothing;
  insert into movements (period_id, product_id, type, qty, note, created_by)
  values (per, p_product, p_type, p_qty, nt, my_name());
  perform log_change(case p_type when 'in' then 'received' else 'removed' end,
                     p_product, per, 'qty', null, fmt(p_qty), nt);
  if p_update_cost and p_cost is not null and is_admin() then
    select buy into old_cost from product_costs where product_id = p_product;
    insert into product_costs (product_id, buy) values (p_product, p_cost)
      on conflict (product_id) do update set buy = excluded.buy;
    perform log_change('price', p_product, null, 'buy price', fmt(old_cost), fmt(p_cost), 'from delivery');
  end if;
end $$;

create function public.delete_movement(p_id bigint) returns void
language plpgsql security definer set search_path = public as $$
declare m movements;
begin
  perform need('admin');
  select * into m from movements where id = p_id;
  if not found then return; end if;
  delete from movements where id = p_id;
  perform log_change('delivery deleted', m.product_id, m.period_id, 'qty', fmt(m.qty), null,
                     case m.type when 'in' then 'received' else 'removed' end);
end $$;

create function public.set_opening(p_product bigint, p_qty numeric) returns void
language plpgsql security definer set search_path = public as $$
declare
  per bigint := open_period_id();
  old numeric;
begin
  perform need('admin');
  if per is null then raise exception 'No open stock take'; end if;
  if p_qty is null or p_qty < 0 then raise exception 'Opening must be zero or more'; end if;
  insert into lines (period_id, product_id) values (per, p_product) on conflict do nothing;
  select opening into old from lines where period_id = per and product_id = p_product;
  update lines set opening = p_qty where period_id = per and product_id = p_product;
  perform log_change('edit', p_product, per, 'opening', fmt(old), fmt(p_qty), null);
end $$;

-- ---------------------------------------------------------------- products

create function public.add_product(p_name text, p_category text, p_sell numeric,
                                   p_buy numeric default null, p_opening numeric default 0) returns bigint
language plpgsql security definer set search_path = public as $$
declare
  nm  text := regexp_replace(trim(coalesce(p_name, '')), '\s+', ' ', 'g');
  cat text := coalesce(nullif(trim(p_category), ''), 'Other');
  pid bigint;
  per bigint := open_period_id();
begin
  perform need('add_products');
  if nm = '' then raise exception 'Product name is required'; end if;
  if exists (select 1 from products where lower(name) = lower(nm)) then
    raise exception '"%" already exists', nm;
  end if;
  if p_opening < 0 or p_sell < 0 or p_buy < 0 then raise exception 'Numbers cannot be negative'; end if;
  insert into products (name, category, sell) values (nm, cat, p_sell) returning id into pid;
  if p_buy is not null and has_perm('see_prices') then
    insert into product_costs (product_id, buy) values (pid, p_buy);
  end if;
  if per is not null then
    insert into lines (period_id, product_id) values (per, pid);
    if coalesce(p_opening, 0) > 0 then
      insert into movements (period_id, product_id, type, qty, note, created_by)
      values (per, pid, 'in', p_opening, 'stock on hand when product was added', my_name());
    end if;
  end if;
  perform log_change('new product', pid, per, null, null, null,
                     'category ' || cat || coalesce(', sell ' || fmt(p_sell), '')
                     || case when coalesce(p_opening, 0) > 0 then ', stock ' || fmt(p_opening) else '' end);
  return pid;
end $$;

create function public.update_product(p_id bigint, p_name text, p_category text, p_sell numeric,
                                      p_buy numeric, p_reorder numeric, p_active boolean) returns void
language plpgsql security definer set search_path = public as $$
declare
  p   products;
  ob  numeric;
  nm  text := regexp_replace(trim(coalesce(p_name, '')), '\s+', ' ', 'g');
  cat text := coalesce(nullif(trim(p_category), ''), 'Other');
  per bigint := open_period_id();
begin
  perform need('admin');
  select * into p from products where id = p_id for update;
  if not found then raise exception 'Unknown product'; end if;
  if nm = '' then nm := p.name; end if;
  if exists (select 1 from products where lower(name) = lower(nm) and id <> p_id) then
    raise exception 'Another product is already called "%"', nm;
  end if;
  select buy into ob from product_costs where product_id = p_id;
  update products set name = nm, category = cat, sell = p_sell,
         reorder_level = coalesce(p_reorder, 0), active = coalesce(p_active, true)
   where id = p_id;
  insert into product_costs (product_id, buy) values (p_id, p_buy)
    on conflict (product_id) do update set buy = excluded.buy;
  if p.name <> nm then perform log_change('product edit', p_id, null, 'name', p.name, nm, null); end if;
  if p.category <> cat then perform log_change('product edit', p_id, null, 'category', p.category, cat, null); end if;
  if p.sell is distinct from p_sell then perform log_change('product edit', p_id, null, 'sell price', fmt(p.sell), fmt(p_sell), null); end if;
  if ob is distinct from p_buy then perform log_change('product edit', p_id, null, 'buy price', fmt(ob), fmt(p_buy), null); end if;
  if p.reorder_level is distinct from coalesce(p_reorder, 0) then
    perform log_change('product edit', p_id, null, 'reorder at', fmt(p.reorder_level), fmt(coalesce(p_reorder, 0)), null);
  end if;
  if p.active is distinct from coalesce(p_active, true) then
    perform log_change('product edit', p_id, null, 'active', p.active::text, coalesce(p_active, true)::text, null);
  end if;
  if coalesce(p_active, true) and per is not null then
    insert into lines (period_id, product_id) values (per, p_id) on conflict do nothing;
  end if;
end $$;

-- ---------------------------------------------------------------- closing a stock take

create function public.close_period(p_closed_name text, p_new_name text) returns bigint
language plpgsql security definer set search_path = public as $$
declare
  per  bigint := open_period_id();
  newp bigint;
  unc  int;
  old_name text;
begin
  perform need('close');
  if per is null then raise exception 'No open stock take'; end if;
  insert into lines (period_id, product_id) select per, id from products where active on conflict do nothing;
  select count(*) into unc from lines where period_id = per and closing is null;

  -- Not counted: assume nothing sold, closing = opening + received - removed.
  with mv as (
    select product_id, sum(case when type = 'in' then qty else -qty end) as net
      from movements where period_id = per group by product_id
  )
  update lines l
     set closing = coalesce(l.closing, l.opening + coalesce(mv.net, 0)),
         sell = p.sell
    from products p left join mv on mv.product_id = p.id
   where l.period_id = per and p.id = l.product_id;

  insert into line_costs (period_id, product_id, buy)
  select per, l.product_id, c.buy
    from lines l join product_costs c on c.product_id = l.product_id
   where l.period_id = per
  on conflict (period_id, product_id) do update set buy = excluded.buy;

  select name into old_name from periods where id = per;
  update periods set status = 'closed', closed_at = now(), closed_by = my_name(),
         name = coalesce(nullif(trim(p_closed_name), ''), name)
   where id = per;

  insert into periods (name)
  values (coalesce(nullif(trim(p_new_name), ''), 'Stock take from ' || to_char(now(), 'DD Mon YYYY')))
  returning id into newp;

  insert into lines (period_id, product_id, opening)
  select newp, l.product_id, l.closing
    from lines l join products p on p.id = l.product_id
   where l.period_id = per and p.active;

  perform log_change('close period', null, per, null, null, null,
                     format('Closed "%s" (%s not counted, assumed unsold) and started a new stock take',
                            coalesce(nullif(trim(p_closed_name), ''), old_name), unc));
  return newp;
end $$;

-- ---------------------------------------------------------------- accounts

create function public._create_user(p_username text, p_full_name text, p_password text,
                                    p_role text, p_perms text[]) returns uuid
language plpgsql security definer set search_path = public, extensions as $$
declare
  uid uuid := gen_random_uuid();
  un  text := lower(trim(p_username));
  em  text := un || '@users.sapphire-stock.app';
begin
  if un !~ '^[a-z0-9._-]{3,30}$' then
    raise exception 'Username: 3-30 lowercase letters, numbers, dots or dashes';
  end if;
  if length(coalesce(p_password, '')) < 8 then raise exception 'Password must be at least 8 characters'; end if;
  if p_role not in ('admin', 'worker') then raise exception 'Invalid role'; end if;
  if exists (select 1 from profiles where username = un) then raise exception 'That username is taken'; end if;

  insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                          raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                          confirmation_token, recovery_token, email_change_token_new, email_change)
  values ('00000000-0000-0000-0000-000000000000', uid, 'authenticated', 'authenticated', em,
          crypt(p_password, gen_salt('bf')), now(),
          '{"provider":"email","providers":["email"]}'::jsonb, jsonb_build_object('username', un),
          now(), now(), '', '', '', '');
  insert into auth.identities (id, user_id, provider_id, identity_data, provider,
                               last_sign_in_at, created_at, updated_at)
  values (gen_random_uuid(), uid, uid::text,
          jsonb_build_object('sub', uid::text, 'email', em, 'email_verified', true),
          'email', now(), now(), now());
  insert into profiles (id, username, full_name, role, perms, active, must_change)
  values (uid, un, nullif(trim(p_full_name), ''), p_role,
          array(select unnest(p_perms) intersect select unnest(allowed_perms())), true, true);
  return uid;
end $$;

create function public.admin_create_user(p_username text, p_full_name text, p_password text,
                                         p_role text, p_perms text[]) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  uid uuid;
  ps  text[];
begin
  perform need('admin');
  uid := _create_user(p_username, p_full_name, p_password, p_role, p_perms);
  select perms into ps from profiles where id = uid;
  perform log_change('user added', null, null, null, null, null,
                     format('%s (%s): %s', lower(trim(p_username)), p_role,
                            coalesce(nullif(array_to_string(ps, ', '), ''), 'no permissions')));
  return uid;
end $$;

create function public.admin_update_user(p_id uuid, p_full_name text, p_role text,
                                         p_perms text[], p_active boolean) returns void
language plpgsql security definer set search_path = public as $$
declare
  u profiles;
  ps text[] := array(select unnest(p_perms) intersect select unnest(allowed_perms()));
begin
  perform need('admin');
  select * into u from profiles where id = p_id;
  if not found then raise exception 'Unknown user'; end if;
  if p_role not in ('admin', 'worker') then raise exception 'Invalid role'; end if;
  if p_id = auth.uid() and (p_role <> 'admin' or not p_active) then
    raise exception 'You cannot remove your own admin access';
  end if;
  update profiles set full_name = nullif(trim(p_full_name), ''), role = p_role, perms = ps, active = p_active
   where id = p_id;
  perform log_change('user limits', null, null, null, null, null,
                     format('%s (%s%s): %s', u.username, p_role, case when p_active then '' else ', disabled' end,
                            coalesce(nullif(array_to_string(ps, ', '), ''), 'no permissions')));
end $$;

create function public.admin_set_password(p_id uuid, p_password text) returns void
language plpgsql security definer set search_path = public, extensions as $$
declare un text;
begin
  perform need('admin');
  if length(coalesce(p_password, '')) < 8 then raise exception 'Password must be at least 8 characters'; end if;
  select username into un from profiles where id = p_id;
  if not found then raise exception 'Unknown user'; end if;
  update auth.users set encrypted_password = crypt(p_password, gen_salt('bf')), updated_at = now() where id = p_id;
  update profiles set must_change = (p_id <> auth.uid()) where id = p_id;
  perform log_change('password reset', null, null, null, null, null, un);
end $$;

create function public.change_my_password(p_old text, p_new text) returns void
language plpgsql security definer set search_path = public, extensions as $$
declare h text;
begin
  if not is_active() then raise exception 'Not signed in'; end if;
  select encrypted_password into h from auth.users where id = auth.uid();
  if h is null or crypt(p_old, h) <> h then raise exception 'Current password is wrong'; end if;
  if length(coalesce(p_new, '')) < 8 then raise exception 'New password must be at least 8 characters'; end if;
  update auth.users set encrypted_password = crypt(p_new, gen_salt('bf')), updated_at = now() where id = auth.uid();
  update profiles set must_change = false where id = auth.uid();
end $$;

create function public.mark_changes_seen() returns void
language plpgsql security definer set search_path = public as $$
begin
  perform need('admin');
  update changes set seen = true where not seen;
end $$;

-- ---------------------------------------------------------------- security

alter table public.profiles      enable row level security;
alter table public.products      enable row level security;
alter table public.product_costs enable row level security;
alter table public.periods       enable row level security;
alter table public.lines         enable row level security;
alter table public.line_costs    enable row level security;
alter table public.movements     enable row level security;
alter table public.changes       enable row level security;

create policy "own or admin"   on public.profiles      for select to authenticated using (id = auth.uid() or is_admin());
create policy "signed in"      on public.products      for select to authenticated using (is_active());
create policy "see prices"     on public.product_costs for select to authenticated using (has_perm('see_prices'));
create policy "signed in"      on public.periods       for select to authenticated using (is_active());
create policy "signed in"      on public.lines         for select to authenticated using (is_active());
create policy "see prices"     on public.line_costs    for select to authenticated using (has_perm('see_prices'));
create policy "signed in"      on public.movements     for select to authenticated using (is_active());
create policy "admin only"     on public.changes       for select to authenticated using (is_admin());

-- Reads only through the policies above; all writes go through the functions.
revoke insert, update, delete, truncate on all tables in schema public from anon, authenticated;
revoke select on all tables in schema public from anon;
revoke execute on all functions in schema public from public, anon, authenticated;
grant execute on function
  public.is_active(), public.is_admin(), public.has_perm(text),
  public.set_count(bigint, numeric),
  public.add_movement(bigint, text, numeric, text, numeric, boolean),
  public.delete_movement(bigint), public.set_opening(bigint, numeric),
  public.add_product(text, text, numeric, numeric, numeric),
  public.update_product(bigint, text, text, numeric, numeric, numeric, boolean),
  public.close_period(text, text),
  public.admin_create_user(text, text, text, text, text[]),
  public.admin_update_user(uuid, text, text, text[], boolean),
  public.admin_set_password(uuid, text), public.change_my_password(text, text),
  public.mark_changes_seen()
to authenticated;

-- Live updates on every device.
alter publication supabase_realtime add table
  public.products, public.product_costs, public.periods, public.lines,
  public.movements, public.changes, public.profiles;
